### ISSUE TITLE
[EPIC] Queries: Frontend app requred queries

### ISSUE THREAD

**Issue by MSalopek** [informalsystems/hydro#80]
During FE prototyping it was discovered that we need more queries to be made available on hydro and tribute contracts.

This issue contains a wishlist of all queries that the FE needs. Details are available in the specific tasks.

If a query will not be provided, please advise how to obtain the required data without a special query.

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/hydro/issues/81
- [ ] https://github.com/informalsystems/hydro/issues/82
- [ ] https://github.com/informalsystems/hydro/issues/83
- [ ] https://github.com/informalsystems/hydro/issues/84
```
